# Site settings
title:          Tech Notes
description:    "Some handy notes that I keep here for easy access"
baseurl:        "/Notes"
url:            "https://malekatwiz.github.io"

# Author
author:
  name:         Malek Atwiz
  url:          https://malekatwiz.github.io
  email:        malek.atwiz@hotmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:title
paginate:       5
